parameters:
  vmImage:

jobs:
  - job: Test_${{ parameters.platform }}
    displayName: Test ${{ parameters.platform }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    variables:
      GO111MODULE: on

    steps:
      - task: GoTool@0
        displayName: 'Use Go 1.12'
        inputs:
          version: 1.12

      - task: Go@0
        displayName: 'Run tests'
        inputs:
          command: test
          arguments: -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... -v ./...

      - task: Go@0
        displayName: 'Build'
        inputs:
          command: build
          arguments: -v ./...

      - script: bash <(curl -s https://codecov.io/bash)
        condition: succeeded()
        displayName: "Upload coverage information to codecov.io"
