project_name: terraform-provider-commercetools

builds:
  - binary: terraform-provider-commercetools_v{{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  name_template: "terraform-provider-commercetools-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
    - goos: linux
      format: zip
    - goos: darwin
      format: zip
  files:
    - none*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brew:
  description: Terraform provider for Commercetools
  homepage: https://github.com/labd/terraform-provider-commercetools
  url_template: https://github.com/labd/terraform-provider-commercetools/releases/download/{{ .Version }}/terraform-provider-commercetools-{{ .Version }}-{{ .Os }}-{{ .Arch }}.zip
  caveats: |
    After installation, you must symlink the provider into Terraform's plugins directory.
    mkdir -p ~/.terraform.d/plugins/
    ln -sf /usr/local/Cellar/terraform-provider-commercetools/$VERSION/bin/terraform-provider-commercetools ~/.terraform.d/plugins/terraform-provider-commercetools
    Symlinking is necessary because Homebrew is sandboxed and cannot write to your home directory.
    Replace $VERSION above.
    If Homebrew is installing somewhere other than /usr/local/Cellar, update the path as well.
  install: |
    bin.install "terraform-provider-commercetools"
  test: |
    system "#{bin}/terraform-provider-commercetools", "-h"  # running bin directly gives error, exit code 1
  github:
    owner: labd
    name: homebrew-terraform-provider-commercetools
  skip_upload: true
