resources:
    containers:
        - container: commercetools
          image: labdigital/commercetools-mock-server
          ports:
              - 8989:8989

jobs:
    - template: jobs/test-ubuntu.yml
      parameters:
          vmImage: ubuntu-16.04
          platform: ubuntu

    - template: jobs/test-macos.yml
      parameters:
          vmImage: macOS-10.13
          platform: macos
